[package]
name = "spectacles"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gateway", "brokers/*"]

[dependencies]
bincode = { version = "2.0.0-rc.2", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
