[package]
name = "spectacles-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
base64 = "0.13.0"
rmp-serde = "1.1.1"
serde-transcode = "1.1.1"
serde_json = "1.0.87"
